apiVersion: v1
kind: ConfigMap
metadata:
  name: accounting-config
data:
  # Database connection details (non-sensitive)
  DB_HOST: "accounting-db-service"
  DB_PORT: "5432"
  DB_NAME: "banking_account_db"
  PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: accounting-secret
type: Opaque
data:
  # Sensitive database credentials (Base64 encoded)
  # banking_user -> YmFua2luZ191c2Vy
  DB_USER: "YmFua2luZ191c2Vy" 
  # secret_password -> c2VjcmV0X3Bhc3N3b3Jk
  DB_PASSWORD: "c2VjcmV0X3Bhc3N3b3Jk"