apiVersion: v1
kind: Service
metadata:
  name: transaction-db
  namespace: transaction-service
spec:
  selector:
    app: transaction-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
