# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-config
#   namespace: banking
# data:
#   prometheus.yml: |
#     global:
#       scrape_interval: 5s

#     scrape_configs:
#       - job_name: 'transaction-service'
#         static_configs:
#           - targets: ['transaction-service.banking.svc.cluster.local:8082']

#       - job_name: 'account-service'
#         static_configs:
#           - targets: ['account-service.banking.svc.cluster.local:8083']

#       - job_name: 'rabbitmq'
#         metrics_path: /metrics
#         static_configs:
#           - targets: ['rabbitmq.banking.svc.cluster.local:15692']

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: transaction-service
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'transaction-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['transaction-service.banking.svc.cluster.local:8082']
