apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-config
  namespace: transaction-service
data:
  ACCOUNT_SERVICE_URL: "http://localhost:8085"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  PGHOST: "transaction-db"
  PGUSER: "txn_user"
  PGPASSWORD: "txn_pass"
  PGDATABASE: "transaction_db"
  PGPORT: "5432"
